---
- name: "Épicerie Le Détour Ansible playbook"
  hosts: webservers
  become: true
  tasks:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest

    - name: Install needed packages
      apt:
        pkg:
          - git
          - nginx
          - rsync
          - wget
          - ufw

    - name: Fetching public keys
      import_tasks: tasks/fetching_keys.yml
