---
- name: "Épicerie Le Détour Ansible playbook"
  hosts: webservers
  become: true
  tasks:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest

    - name: Install needed packages
      apt:
        pkg:
          - git
          - nginx
          - rsync
          - wget

    - name: Setup charlesfleches keys
      authorized_key:
          user: debian
          state: present
          key: https://github.com/charlesfleche.keys 
          path: .ssh/authorized_keys 

    - name: Setup mauriandres keys
      authorized_key:
          user: debian
          state: present
          key: https://github.com/mauriandres.keys 
          path: .ssh/authorized_keys 

    - name: Setup Wmbat keys
      authorized_key:
          user: debian
          state: present
          key: https://github.com/Wmbat.keys 
          path: .ssh/authorized_keys 
