- name: Disable all ports
  ufw:
    state: disabled
    policy: deny

- name: Open port 22 for SSH
  ufw:
    rule: allow
    port: '22'

- name: Open port 3000 for Grafana
  ufw:
    rule: allow
    port: '3000'
