- name: Add Grafana repository key
  apt_key:
      url: 'https://packages.grafana.com/gpg.key'
      state: present

- name: Add Grafana Repository
  apt_repository:
      repo: 'deb https://packages.grafana.com/oss/deb stable main'
      state: present

- name: Install Grafana
  apt:
    update_cache: yes
    pkg: 
      - grafana

- name: Start Grafana
  systemd:
      name: grafana-server
      state: started
