- name: Loki Download
  get_url:
      url: "https://github.com/grafana/loki/releases/download/v1.5.0/loki-linux-amd64.zip"
      dest: /usr/local/bin/loki.gz

- name: Unzip Loki
  unarchive:
      src: /usr/local/bin/loki.gz
      dest: /usr/local/bin/
      remote_src: yes
      mode: "a+x"

- name: Copying Loki systemd service config
  copy:
      src: ./files/loki.service
      dest: /etc/systemd/system/

- name: Copying Loki config
  copy:
      src: ./files/config-loki.yml
      dest: /usr/local/bin/

- name: Start Loki
  systemd:
      name: loki
      enabled: true
      state: started

- name: Promtail Download
  get_url:
      url: "https://github.com/grafana/loki/releases/download/v1.5.0/promtail-linux-amd64.zip"
      dest: /usr/local/bin/promtail.gz

- name: Unzip Promtail
  unarchive:
      src: /usr/local/bin/promtail.gz
      dest: /usr/local/bin/
      remote_src: yes
      mode: "a+x"

- name: Copying Promtail service config
  copy:
      src: ./files/promtail.service
      dest: /etc/systemd/system/

- name: Copying promtail config
  copy:
      src: ./files/config-promtail.yml
      dest: /usr/local/bin/

- name: Start promtail
  systemd:
      name: promtail
      enabled: true
      state: started
