- name: Enable unattended upgrades
  lineinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      line: 'APT::Periodic::Enable "1";'
      insertbefore: BOF

- name: Enable autoclean
  lineinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      line: 'APT::Periodic::AutocleanInterval "7";'

- name: Remove non-security upgrades
  replace:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '"origin=Debian,codename=${distro_codename},label=Debian";'
      replace: '// "origin=Debian,codename=${distro_codename},label=Debian";'
