- name: Activate unattended-upgrades
  block:
    - name: Update debconf parameters
      debconf:
        name: 'unattended-upgrades'
        question: 'unattended-upgrades/enable_auto_updates'
        value: 'true'
        vtype: 'boolean'
    - name: Reconfigure dpkg
      command: dpkg-reconfigure -f noninteractive unattended-upgrades creates=/etc/apt/apt.conf.d/20auto-upgrades

- name: Remove non-security upgrades
  lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: 'label=Debian";'
      state: absent
