server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /tmp/positions.yaml

# Loki Server URL
clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: ufw
    static_configs:
      - targets:
          - localhost
        labels:
          job: ufw
          host: localhost
          __path__: /var/log/ufw.log
