server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /var/positions.yaml

# Loki Server URL
clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: ufw
    static_configs:
      - targets:
          - localhost
        labels:
          job: ufw
          __path__: /var/log/ufw.log

  - job_name: fail2ban
    static_configs:
      - targets:
          - localhost
        labels:
          job: fail2ban
          __path__: /var/log/fail2ban.log

  - job_name: ssh
    static_configs:
      - targets:
          - localhost
        labels:
          job: ssh
          __path__: /var/log/auth.log

  - job_name: borg
    pipeline_stages:
    - json:
        expressions:
            archive: archive
    - labels:
        archive:
    - output:
        source: output 
    static_configs:
      - targets:
          - localhost
        labels:
          job: borg
          __path__: /var/log/borg.log
